# Generated by Django 5.2 on 2025-07-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='navigation_id',
            field=models.CharField(blank=True, help_text='Navigation identifier for the frontend', max_length=20, null=True),
        ),
    ]
