# Generated by Django 5.2 on 2025-07-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_avg_rating_car_total_reviews'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_car', 'موافقة على سيارة'), ('reject_car', 'رفض سيارة'), ('approve_document', 'موافقة على مستند'), ('reject_document', 'رفض مستند'), ('suspend_user', 'حظر مستخدم'), ('activate_user', 'تفعيل مستخدم'), ('cancel_rental', 'إلغاء رحلة'), ('resolve_report', 'حل بلاغ'), ('delete_rating', 'حذف تقييم')], max_length=30)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiring_document', 'مستند منتهي الصلاحية'), ('high_priority_report', 'بلاغ عالي الأولوية'), ('suspicious_activity', 'نشاط مشبوه'), ('system_error', 'خطأ في النظام'), ('payment_issue', 'مشكلة في الدفع')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=20, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('car', 'سيارة'), ('document', 'مستند'), ('user', 'مستخدم'), ('rental', 'رحلة'), ('report', 'بلاغ')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('partially_approved', 'موافق جزئياً')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('verification_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='CarVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('partially_approved', 'موافق جزئياً')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('images_verified', models.BooleanField(default=False)),
                ('pricing_verified', models.BooleanField(default=False)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_verifications', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cars.car')),
            ],
            options={
                'ordering': ['-verified_at'],
                'unique_together': {('car', 'admin_user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('partially_approved', 'موافق جزئياً')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_verifications', to='documents.document')),
            ],
            options={
                'ordering': ['-verified_at'],
                'unique_together': {('document', 'admin_user')},
            },
        ),
    ]
