# Generated by Django 5.2 on 2025-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
