# Generated by Django 5.2 on 2025-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrole',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userrole',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
