# Generated by Django 5.2 on 2025-06-30 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'rental_content_type', 'rental_object_id', 'reviewee_content_type', 'reviewee_object_id')},
        ),
    ]
