# Generated by Django 5.2 on 2025-07-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('selfdrive_rentals', '0008_selfdrivecontract_owner_pickup_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdriverental',
            name='selected_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfdrive_rentals', to='payments.savedcard'),
        ),
    ]
