# Generated by Django 5.2 on 2025-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0009_selfdriverental_selected_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdrivelivelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='selfdrivelivelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='selfdriverental',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='selfdriverental',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='selfdriverental',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='selfdriverental',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
