# Generated by Django 5.2 on 2025-05-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by', models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter')], max_length=10)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stٍart_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Confirmed', 'Confirmed'), ('Awaiting Deposit', 'Awaiting Deposit'), ('Deposit Paid', 'Deposit Paid'), ('Awaiting Contract', 'Awaiting Contract'), ('contractSigned', 'Contract Signed'), ('Awaiting Final Payment', 'Awaiting Final Payment'), ('Final Payment Paid', 'Final Payment Paid'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Pending', max_length=30)),
                ('negotiation_status', models.CharField(choices=[('NotNegotiated', 'Not Negotiated'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('OwnerRejected', 'Owner Rejected'), ('RenterRejected', 'Renter Rejected'), ('OwnerAccepted', 'Owner Accepted'), ('RenterAccepted', 'Renter Accepted')], default='NotNegotiated', max_length=30)),
                ('rental_type', models.CharField(choices=[('WithDriver', 'With Driver'), ('WithoutDriver', 'Without Driver')], default='WithDriver', max_length=20)),
                ('rental_zone_WithoutDriver', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trip', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by_type', models.CharField(choices=[('System', 'System'), ('Owner', 'Owner'), ('Renter', 'Renter')], default='System', max_length=10)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_logs', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('insurance_paid_at', models.DateTimeField(blank=True, null=True)),
                ('insurance_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rental_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('rental_paid_at', models.DateTimeField(blank=True, null=True)),
                ('rental_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal')], default='Cash', max_length=10)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_distance_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('extra_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_km_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_hour_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickup_confirmed_by_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('pickup_confirmed_by_renter', models.BooleanField(blank=True, default=False, null=True)),
                ('dropoff_confirmed_by_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('dropoff_confirmed_by_renter', models.BooleanField(blank=True, default=False, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_info', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('approx_waiting_time_minutes', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('planned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rentals.plannedtrip')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('planned_trip', 'stop_order')},
            },
        ),
    ]
