# Generated by Django 5.2 on 2025-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtripstop',
            name='actual_waiting_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedtripstop',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannedtripstop',
            name='waiting_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedtripstop',
            name='waiting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('electronic', 'Electronic')], default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='driver_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='insurance_buffer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('visa', 'Visa/Mastercard'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='refundable_buffer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalusage',
            name='extra_waiting_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalusage',
            name='total_waiting_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalusage',
            name='waiting_time_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
