# Generated by Django 5.2 on 2025-06-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_extra_hour_charges_rentalusage_total_waiting_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalUsage',
        ),
    ]
