# Generated by Django 5.2 on 2025-06-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_plannedtripstop_actual_waiting_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='proposed_price',
        ),
    ]
