# Generated by Django 5.2 on 2025-06-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_rental_proposed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='proposed_by',
        ),
    ]
