# Generated by Django 5.2 on 2025-07-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('rentals', '0003_delete_rentalusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='selected_card',
            field=models.ForeignKey(blank=True, help_text='Pre-selected card for deposit and remaining payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_rentals', to='payments.savedcard'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PendingOwnerConfirmation', 'Pending Owner Confirmation'), ('DepositRequired', 'Deposit Required'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='PendingOwnerConfirmation', max_length=30),
        ),
    ]
