# Generated by Django 5.2 on 2025-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_rental_proposed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtripstop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
