# Generated by Django 5.2 on 2025-07-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_add_selected_card_to_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='deposit_due_at',
            field=models.DateTimeField(blank=True, help_text='Deposit payment deadline (like self-drive)', null=True),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='excess_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charges at end of trip', max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='excess_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='excess_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='excess_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('PendingOwnerConfirmation', 'Pending Owner Confirmation'), ('DepositRequired', 'Deposit Required'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='PendingOwnerConfirmation', max_length=30),
        ),
    ]
