# Generated by Django 5.2 on 2025-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalpayment_deposit_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbreakdown',
            name='actual_total_waiting_minutes',
            field=models.IntegerField(default=0, help_text='Actual waiting minutes at end of trip'),
        ),
        migrations.AddField(
            model_name='rentalbreakdown',
            name='excess_waiting_cost',
            field=models.FloatField(default=0, help_text='Cost of extra waiting'),
        ),
        migrations.AddField(
            model_name='rentalbreakdown',
            name='extra_waiting_minutes',
            field=models.IntegerField(default=0, help_text='Extra waiting beyond planned'),
        ),
        migrations.AddField(
            model_name='rentalbreakdown',
            name='final_total_cost',
            field=models.FloatField(default=0, help_text='Final cost including all excess charges'),
        ),
        migrations.AlterField(
            model_name='rentalbreakdown',
            name='final_cost',
            field=models.FloatField(default=0, help_text='Final cost without end-of-trip excess'),
        ),
        migrations.AlterField(
            model_name='rentalbreakdown',
            name='total_waiting_minutes',
            field=models.IntegerField(default=0, help_text='Planned waiting minutes'),
        ),
    ]
