# Generated by Django 5.2 on 2025-06-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_plannedtripstop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_km', models.FloatField(default=0)),
                ('total_waiting_minutes', models.IntegerField(default=0)),
                ('daily_price', models.FloatField(default=0)),
                ('extra_km_cost', models.FloatField(default=0)),
                ('waiting_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('buffer_amount', models.FloatField(default=0)),
                ('deposit', models.FloatField(default=0)),
                ('platform_fee', models.FloatField(default=0)),
                ('driver_earnings', models.FloatField(default=0)),
                ('allowed_km', models.FloatField(default=0)),
                ('extra_km', models.FloatField(default=0)),
                ('base_cost', models.FloatField(default=0)),
                ('final_cost', models.FloatField(default=0)),
                ('commission_rate', models.FloatField(default=0.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='rentals.rental')),
            ],
        ),
    ]
