# Generated by Django 5.2 on 2025-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentalbreakdown_actual_total_waiting_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='owner_arrival_confirmed',
            field=models.BooleanField(default=False, help_text='Whether owner confirmed arrival at pickup location'),
        ),
        migrations.AddField(
            model_name='rental',
            name='owner_arrived_at_pickup',
            field=models.DateTimeField(blank=True, help_text='When owner confirmed arrival at pickup location', null=True),
        ),
    ]
