# Generated by Django 5.2 on 2025-06-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentalbreakdown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='stٍart_date',
            new_name='start_date',
        ),
    ]
