# Generated by Django 5.2 on 2025-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rental_owner_arrival_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='renter_on_way_announced',
            field=models.BooleanField(default=False, help_text='Whether renter announced they are on the way'),
        ),
        migrations.AddField(
            model_name='rental',
            name='renter_on_way_announced_at',
            field=models.DateTimeField(blank=True, help_text='When renter announced they are on the way', null=True),
        ),
    ]
