# Generated by Django 5.2 on 2025-07-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rental_renter_on_way_announced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
