# Generated by Django 5.2 on 2025-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rental_dropoff_lat_alter_rental_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtripstop',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plannedtripstop',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
