# Generated by Django 5.2 on 2025-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_update_coordinates_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtripstop',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='plannedtripstop',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
